#+-----------------------------------+
#| Created by: fgatto13 @2026-02-10  |
#+-----------------------------------+
# patients.py

import azure.functions as func
import logging
import json
import uuid

from auth import validate_jwt
from utils import cors_response, add_cors_headers

# ---- Route Handlers ----

def patients_route(req: func.HttpRequest) -> func.HttpResponse:
    """
    Handles /patients for GET (list) and POST (create)
    """
    if req.method == "OPTIONS":
        return cors_response()

    auth_header = req.headers.get("Authorization")
    if not auth_header:
        return add_cors_headers(func.HttpResponse("Unauthorized: No auth header found", status_code=401))

    # Ensure it starts with "Bearer " and has a token
    parts = auth_header.split(" ", 1)
    if len(parts) != 2 or parts[0] != "Bearer" or not parts[1]:
        return add_cors_headers(func.HttpResponse("Malformed Authorization header", status_code=401))

    token = parts[1]

    try:
        claims = validate_jwt(token)
    except ValueError:
        return add_cors_headers(func.HttpResponse("Unauthorized: token validation error", status_code=401))
    roles = claims.get("roles") or []

    if req.method == "GET":
        logging.info("list_patients endpoint called")
        patients_bundle = {
            "resourceType": "Bundle",
            "type": "searchset",
            "total": 2,
            "entry": [
                {
                    "resource": {
                        "resourceType": "Patient",
                        "id": "1",
                        "name": [{"family": "Rossi", "given": ["Mario"]}],
                        "gender": "male"
                    }
                },
                {
                    "resource": {
                        "resourceType": "Patient",
                        "id": "2",
                        "name": [{"family": "Bianchi", "given": ["Luisa"]}],
                        "gender": "female"
                    }
                }
            ]
        }
        return add_cors_headers(func.HttpResponse(
            body=json.dumps(patients_bundle),
            status_code=200,
            mimetype="application/json"
        ))

    elif req.method == "POST":
        logging.info("create_patient endpoint called")
        if not any(r in roles for r in ["User.Admin", "User.Doctor"]):
            return add_cors_headers(func.HttpResponse("Forbidden", status_code=403))

        try:
            patient_payload = req.get_json()
        except ValueError:
            return add_cors_headers(func.HttpResponse("Invalid JSON body", status_code=400))

        if patient_payload.get("resourceType") != "Patient":
            return add_cors_headers(func.HttpResponse("Payload must be a Patient resource", status_code=400))

        if "id" in patient_payload:
            return add_cors_headers(func.HttpResponse(
                "New Patient cannot include an ID; it will be generated by the server",
                status_code=400
            ))

        # Temporary structure: mock patient ID generation
        patient_payload["id"] = str(uuid.uuid4())

        return add_cors_headers(func.HttpResponse(
            body=json.dumps(patient_payload),
            status_code=201,
            mimetype="application/json"
        ))

    else:
        return add_cors_headers(func.HttpResponse("Method not allowed", status_code=405))


def get_patient_route(req: func.HttpRequest) -> func.HttpResponse:
    """
    Handles /patients/{patient_id} GET
    """
    if req.method == "OPTIONS":
        return cors_response()

    logging.info('get_patient endpoint called')
    patient_id = req.route_params.get("patient_id")
    if not patient_id:
        return add_cors_headers(func.HttpResponse("Missing patient_id", status_code=400))

    auth_header = req.headers.get("Authorization")
    if not auth_header:
        return add_cors_headers(func.HttpResponse("Unauthorized: No auth header found", status_code=401))

    # Ensure it starts with "Bearer " and has a token
    parts = auth_header.split(" ", 1)
    if len(parts) != 2 or parts[0] != "Bearer" or not parts[1]:
        return add_cors_headers(func.HttpResponse("Malformed Authorization header", status_code=401))

    token = parts[1]


    patient_data = {
        "resourceType": "Patient",
        "id": patient_id,
        "name": [{"family": "Rossi", "given": ["Mario"]}],
        "gender": "male",
        "birthDate": "1980-01-01"
    }

    return add_cors_headers(func.HttpResponse(
        body=json.dumps(patient_data),
        status_code=200,
        mimetype="application/json"
    ))


def update_patient_route(req: func.HttpRequest) -> func.HttpResponse:
    """
    Handles /patients/{patient_id} PUT
    """
    if req.method == "OPTIONS":
        return cors_response()

    logging.info("update_patient endpoint called")
    auth_header = req.headers.get("Authorization")
    if not auth_header:
        return add_cors_headers(func.HttpResponse("Unauthorized", status_code=401))

    # Ensure it starts with "Bearer " and has a token
    parts = auth_header.split(" ", 1)
    if len(parts) != 2 or parts[0] != "Bearer" or not parts[1]:
        return add_cors_headers(func.HttpResponse("Malformed Authorization header", status_code=401))

    token = parts[1]

    try:
        claims = validate_jwt(token)
    except ValueError:
        return add_cors_headers(func.HttpResponse("Unauthorized: token validation error", status_code=401))
    roles = claims.get("roles") or []

    if not any(r in roles for r in ["User.Admin", "User.Doctor"]):
        return add_cors_headers(func.HttpResponse("Forbidden", status_code=403))

    patient_id = req.route_params.get("patient_id")
    if not patient_id:
        return add_cors_headers(func.HttpResponse("Missing patient_id", status_code=400))

    try:
        patient_payload = req.get_json()
    except ValueError:
        return add_cors_headers(func.HttpResponse("Invalid JSON body", status_code=400))

    if patient_payload.get("resourceType") != "Patient":
        return add_cors_headers(func.HttpResponse("Payload must be a Patient resource", status_code=400))

    if patient_payload.get("id") != patient_id:
        return add_cors_headers(func.HttpResponse("Patient ID mismatch between URL and body", status_code=400))

    # Temporary: mock update
    updated_patient = patient_payload

    return add_cors_headers(func.HttpResponse(
        body=json.dumps(updated_patient),
        status_code=200,
        mimetype="application/json"
    ))
